# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

# 기본으로 생성된 스크립트
# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end


platform :android do
  desc "Submit a new version to the internal testing track"
  # 내부 테스트 트랙으로 배포
  lane :beta do
    gradle(task: "clean")
    gradle(
      task: 'bundle',
      build_type: 'release'
    )
    upload_to_play_store(
      track: 'internal',
      # draft를 넣어서 하면 임시로 배포되기 때문에 구글 플레이 콘솔 가서 직접 배포를 해줘야하고
      # 밑에 줄을 없애면 바로 배포가 된다. 필요에 따라 시나리오를 짜서 사용하면 되겠다.
      release_status: 'draft'
    )
  end

  # 내부 테스트 배포 안하고 바로 프로덕션 트랙으로 배포
  desc "Submit a new version to the production"
  lane :release do
    gradle(task: "clean")
    gradle(
      task: 'bundle',
      build_type: 'release'
    )
    upload_to_play_store(
      track: 'production'
    )
  end
end